sonar.projectKey=quantumtechwld-com_quantumtechwld
sonar.organization=quantumtechwld-com

sonar.projectName=Quantum Technology Agency
sonar.projectVersion=1.0

# Fontes analisadas
sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.spec.ts,**/__tests__/**,**/node_modules/**,**/.next/**,**/prisma/migrations/**

# TypeScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
